config:
  bookmarks:
    - Developer Tools:
        - GitHub:
            - abbr: GH
              href: https://github.com/rainforest-dev
  services:
    - Raspberry Pi 4:
        - Home Assistant:
            href: http://raspberrypi-4:8123
  widgets:
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  kubernetes:
    mode: cluster

serviceAccount:
  create: true
  name: homepage

enableRbac: true

ingress:
  main:
    enabled: true
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Homepage"
      gethomepage.dev/description: "Dynamically Detected Homepage"
      gethomepage.dev/group: "Dynamic"
      gethomepage.dev/icon: "homepage.png"
    hosts:
      - host: homepage.k8s.orb.local
        paths:
          - path: /
            pathType: Prefix
