[tool.poetry]
name = "comfyui"
version = "0.1.0"
description = ""
authors = ["Rainforest Cheng <contact@rainforest.tools>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
